name: "Create Account"
on:
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-20.04
    env:

      # randomize the name in array
      NAME: tung
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: npm run auto
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          # name is today's date
          name: ${{ format('accounts-{0}', github.run_number) }}
          path: ./accounts/*.txt
