name: "Create Account"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    env:
      NAME: ${{ secrets.NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: npm run auto
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          # name is today's date
          name: ${{ github.run_id }}.txt
          path: ./accounts/*.txt
